type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "load customers"
        - "Create_s3_src_customer_acc"
      parameters:
        componentName: "Start"
    load customers:
      type: "database-query"
      parameters:
        componentName: "load customers"
        basicAdvancedMode: "Advanced"
        databaseType: "MariaDB"
        connectionUrl: "jdbc:mariadb://mat-trn-src.co4vks4ks8wo.eu-west-1.rds.amazonaws.com:3306/greenwave"
        username: "greenwave_user"
        password: "RDS-database-password"
        connectionOptions:
        sqlQuery: "SELECT * FROM customers;"
        type: "Standard"
        primaryKeys:
        warehouse1: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "rds_source_customer"
        stage1: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
    Create_s3_src_customer_acc:
      type: "create-table"
      transitions:
        success:
        - "S3 Load src_customer_account"
      parameters:
        componentName: "Create_s3_src_customer_acc"
        createReplace: "Create if not exists"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName: "s3_src_customer_accounts"
        tableType: "Permanent"
        columns:
        - - "DataValue"
          - "VARIANT"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
    S3 Load src_customer_account:
      type: "s3-load"
      parameters:
        componentName: "S3 Load src_customer_account"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://public-online-mtln-training-s3-greenwave/"
        pattern: "customer_accounts.json"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "s3_src_customer_accounts"
        loadColumns:
        - "DataValue"
        format: "[Custom]"
        fileType: "JSON"
        compression: "AUTO"
        enableOctal: "False"
        allowDuplicates: "False"
        stripOuterArray: "False"
        stripNullValues: "False"
        ignoreUtf8Errors: "False"
        nullIf1:
        trimSpace1: "False"
        onError: "Abort Statement"
        sizeLimitB:
        purgeFiles: "False"
        matchByColumnName: "None"
        truncateColumns: "False"
        forceLoad: "False"
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    load customers:
      position:
        x: 120
        "y": 0
      tempMetlId: 3
    Create_s3_src_customer_acc:
      position:
        x: 120
        "y": 120
      tempMetlId: 4
    S3 Load src_customer_account:
      position:
        x: 240
        "y": 120
      tempMetlId: 5
