type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Sharepoint Query"
      parameters:
        componentName: "Start"
    Sharepoint Query:
      type: "sharepoint-query"
      parameters:
        componentName: "Sharepoint Query"
        basicAdvancedMode: "Basic"
        serviceType: "REST"
        authentication: "MOTORPOINT_TEST"
        sharePointEdition: "SharePoint Online"
        connectionOptions:
        dataSource: "Europe"
        dataSelection:
        - "BaseName"
        - "AppAuthorId"
        - "AppEditorId"
        - "Attachments"
        - "AuthorId"
        - "ComplianceAssetId"
        - "ContentTypeId"
        - "Created"
        - "CreatedDate"
        - "DocIcon"
        - "Edit"
        - "EditorId"
        - "EncodedAbsUrl"
        - "FileDirRef"
        - "FileLeafRef"
        - "FileRef"
        - "FileType"
        - "FSObjType"
        - "GUID"
        - "HTMLFileType"
        - "ID"
        - "InstanceID"
        - "LastModified"
        - "LinkedAuthor"
        - "LinkedEditor"
        - "LinkFilename"
        - "LinkFilename2"
        - "LinkFilenameNoMenu"
        - "LinkTitle"
        - "LinkTitle2"
        - "LinkTitleNoMenu"
        - "Modified"
        - "OData__ColorHex"
        - "OData__ColorTag"
        - "OData__CopySource"
        - "OData__EditMenuTableEnd"
        - "OData__EditMenuTableStart"
        - "OData__EditMenuTableStart2"
        - "OData__Emoji"
        - "OData__HasCopyDestinations"
        - "OData__IsCurrentVersion"
        - "OData__IsRecord"
        - "OData__Level"
        - "OData__ModerationComments"
        - "OData__ModerationStatus"
        - "OData__UIVersion"
        - "OData__UIVersionString"
        - "Order"
        - "owshiddenversion"
        - "PermMask"
        - "PrincipalCount"
        - "SelectTitle"
        - "ServerUrl"
        - "Title"
        - "UniqueId"
        - "WorkflowInstanceID"
        - "WorkflowVersion"
        dataSourceFilter:
        combineFilters: "And"
        limit: "100"
        type: "Standard"
        primaryKeys:
        warehouse: "[Environment Default]"
        database: "TEST_DB"
        schema: "TEST_MOTORPOINT"
        targetTable: "test"
        stage: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        autoDebug: "On"
        debugLevel: "1"
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Sharepoint Query:
      position:
        x: 120
        "y": 0
      tempMetlId: 2
